# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token f2c3f56637634dc6f8811dd6c5fbb8425983cf50

{
  "title": "Ребенок",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token f2c3f56637634dc6f8811dd6c5fbb8425983cf50

{
  "status": "CLOSED"
}

###

DELETE {{baseUrl}}/advertisements/3/

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
