# Generated by Django 5.0 on 2024-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_sensor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
