# Generated by Django 5.0 on 2024-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_measurement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='measurements_photos', verbose_name='Фото'),
        ),
    ]
