# Generated by Django 5.0 on 2023-12-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
