# Generated by Django 5.0 on 2023-12-19 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.CharField(default='default_image.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
